# Generated by Django 4.2.13 on 2024-06-07 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rina_app', '0003_alter_embarcacao_table_alter_empresa_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
    ]
