# Generated by Django 4.2.13 on 2024-06-07 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rina_app', '0006_alter_embarcacao_ativo_alter_empresa_ativo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embarcacao',
            name='embarcacao',
            field=models.CharField(max_length=200, verbose_name='Embarcação'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='empresa',
            field=models.CharField(max_length=200, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='gerencia',
            name='gerencia',
            field=models.CharField(max_length=200, verbose_name='Gerência'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='embarcacao_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rina_app.embarcacao', verbose_name='Embarcação'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='empresa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rina_app.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='gerencia_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rina_app.gerencia', verbose_name='Gerência'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='prazo_nuvem',
            field=models.IntegerField(verbose_name='Prazo Nuvem'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rina_app.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='recursos',
            name='tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rina_app.tipo', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=200, verbose_name='Tipo'),
        ),
    ]
