# Generated by Django 4.2.13 on 2024-06-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rina_app', '0007_alter_embarcacao_embarcacao_alter_empresa_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('setor', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'setor',
            },
        ),
    ]
